package user;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class User {

    public User(int userID, String username, String email, String password,Date accountCreationDate) {
        this.userID = userID;
        this.username = username;
        this.email = email;
        this.password = password;
        this.accountCreationDate = accountCreationDate;
        this.isActive = true;
        //to-do subscription

        //Initialize follows to empty
        this.followedUsers = new ArrayList<>();
        this.followers = new ArrayList<>();
    }

    //Identifier
    private final int userID; //uniquely generated by the user manager
    private String username;
    private String email;
    private String password; //hash ?

    public int getUserID() {
        return userID;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    //Personal information
    private String firstName;
    private String lastName;
    private Date dateOfBirth;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    //Account information
    private Date accountCreationDate;
    private boolean isActive;
    //What the user can do
    private SubscriptionPlan subscriptionPlan;
    //Time-related data about subscription
    private SubscriptionInfo subscriptionInfo;

    public Date getAccountCreationDate() {
        return accountCreationDate;
    }

    public void setAccountCreationDate(Date accountCreationDate) {
        this.accountCreationDate = accountCreationDate;
    }

    public SubscriptionPlan getSubscriptionPlan() {
        return subscriptionPlan;
    }

    public void setSubscriptionPlan(SubscriptionPlan subscription) {
        this.subscriptionPlan = subscription;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    public SubscriptionInfo getSubscriptionInfo() {
        return subscriptionInfo;
    }

    public void setSubscriptionInfo(SubscriptionInfo subscriptionInfo) {
        this.subscriptionInfo = subscriptionInfo;
    }

    //Followed Users
    private List<User> followedUsers;
    private List<User> followers;

    public List<User> getFollowedUsers() {
        return followedUsers;
    }

    public void setFollowedUsers(List<User> followedUsers) {
        this.followedUsers = followedUsers;
    }

    public List<User> getFollowers() {
        return followers;
    }

    public void setFollowers(List<User> followers) {
        this.followers = followers;
    }

}
