package user;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import songsOrganisation.Library;
import songsOrganisation.Playlist;


/**
 * User class represents a user in the system.
 * It contains personal information, account information, and subscription details.
 * It also manages the user's followed users and followers.
 */
public class User {
    /**
     * Default constructor for Jackson deserialization.
     * Required for Jackson to properly reconstruct objects from JSON.
     */
    public User() {
        // Initialize empty lists to avoid null pointer exceptions
        List<Playlist> playlists = new ArrayList<>();

        // Create the library using the list
        this.library = new Library(userID, playlists);

        this.followedUsersIDs = new ArrayList<>();
        this.followersIDs = new ArrayList<>();
    }

    public User(int userID, String username, String email, String password,Date accountCreationDate) {
        this.userID = userID;
        this.username = username;
        this.email = email;
        this.password = password;
        this.accountCreationDate = accountCreationDate;
        this.isActive = true;

        // Create default playlist and assign it
        this.defaultPlaylist = new Playlist("Favorites", userID);

        // Create a list with the default playlist
        List<Playlist> playlists = new ArrayList<>();
        playlists.add(defaultPlaylist);

        // Create the library using the list
        this.library = new Library(userID, playlists);

        //Initialize follows to empty
        this.followedUsersIDs = new ArrayList<>();
        this.followersIDs = new ArrayList<>();
    }

    //Identifier
    private int userID; //uniquely generated by the user manager
    private String username;
    private String email;
    private String password; //hash ?

    public int getUserID() {
        return userID;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    //Personal information
    private String firstName;
    private String lastName;
    private Date dateOfBirth;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    //Account information
    private Date accountCreationDate;
    private boolean isActive;
    //What the user can do
    private SubscriptionPlan subscriptionPlan;
    //Time-related data about subscription
    private SubscriptionInfo subscriptionInfo;

    public Date getAccountCreationDate() {
        return accountCreationDate;
    }

    public void setAccountCreationDate(Date accountCreationDate) {
        this.accountCreationDate = accountCreationDate;
    }

    public SubscriptionPlan getSubscriptionPlan() {
        return subscriptionPlan;
    }

    public void setSubscriptionPlan(SubscriptionPlan subscription) {
        this.subscriptionPlan = subscription;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    public SubscriptionInfo getSubscriptionInfo() {
        return subscriptionInfo;
    }

    public void setSubscriptionInfo(SubscriptionInfo subscriptionInfo) {
        this.subscriptionInfo = subscriptionInfo;
    }

    // Library and playlist
    private final Library library;
    private Playlist defaultPlaylist;

    public Library getLibrary() {
        return library;
    }

    public Playlist getDefaultPlaylist() {
        return defaultPlaylist;
    }

    public void setDefaultPlaylist(Playlist defaultPlaylist) {
        this.defaultPlaylist = defaultPlaylist;
    }

    //Followed Users
    private List<Integer> followedUsersIDs;
    private List<Integer> followersIDs;

    public List<Integer> getFollowedUsersIDs() {
        return followedUsersIDs;
    }

    public void setFollowedUsersIDs(List<Integer> followedUsersIDs) {
        this.followedUsersIDs = followedUsersIDs;
    }

    public List<Integer> getFollowersIDs() {
        return followersIDs;
    }

    public void setFollowersIDs(List<Integer> followersIDs) {
        this.followersIDs = followersIDs;
    }

}
