package subscription;

import java.util.Date;
import java.util.List;

public class User {

    public User(int userID) {
        this.userID = userID;
    }

    //Identifier
    private final int userID; //uniquely generated by the user manager
    private String username;
    private String email;
    private String password; //hash ?

    public int getUserID() {
        return userID;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    //Personal information
    private String firstName;
    private String lastName;
    private Date dateOfBirth;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    //Account information
    private Date accountCreationDate;
    private SubscriptionPlan subscription;
    private boolean isActive;

    public Date getAccountCreationDate() {
        return accountCreationDate;
    }

    public void setAccountCreationDate(Date accountCreationDate) {
        this.accountCreationDate = accountCreationDate;
    }

    public SubscriptionPlan getSubscription() {
        return subscription;
    }

    public void setSubscription(SubscriptionPlan subscription) {
        this.subscription = subscription;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    //Followed Users
    private List<User> followedUsers;
    private List<User> followByUsers;


}
