import subscription.SubscriptionPlan;

import java.util.Date;

public class User {
    //Identifier
    private final int userID; //uniquely generated by the user manager
    private String username;
    private String email;
    private String password; //hash ?

    //Personal information
    private String firstName;
    private String lastName;
    private Date dateOfBirth;

    //Account information
    private SubscriptionPlan subscription;
    private Date creationDate;

    public User(int userID) {
        this.userID = userID;
    }
}
